spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/pt_local?zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: pt_local_user
    password: ptlocal123
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20


  batch:
    jdbc:
      initialize-schema: always